### PR TITLE
Initial Merge

### PR DESCRIPTION
**Pull request by fpancald**
This pull request is to pass the current files from my working repository.
All files in the bertini_timing directory needed to install and run the code itself are present here.
However, note that compiled versions of bertini1, berini2, and Eigen are needed in order to compile and use the code in this repository.
I will later add a detailed explanation to the documentation and plan on asking different members of the group to download, install, and run the code on their machines.

fpancald

### CODE REVIEW

**Comment by ofloveandhate** [comment]
on my machine (osx, xcode 8), i get the following compiler errors, related to the use of `chrono`:

```
src/b1_timing.cpp:53:14: error: no viable overloaded '='
    for_start=std::chrono::system_clock::now();//start count for overall time
    ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/chrono:750:29: note: candidate function
      (the implicit copy assignment operator) not viable: no known conversion from 'time_point<std::__1::chrono::system_clock, duration<[...],
      ratio<[...], 1000000>>>' to 'const time_point<std::__1::chrono::steady_clock, duration<[...], ratio<[...], 1000000000>>>' for 1st
      argument
class _LIBCPP_TYPE_VIS_ONLY time_point
                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/chrono:750:29: note: candidate function
      (the implicit move assignment operator) not viable: no known conversion from 'time_point<std::__1::chrono::system_clock, duration<[...],
      ratio<[...], 1000000>>>' to 'time_point<std::__1::chrono::steady_clock, duration<[...], ratio<[...], 1000000000>>>' for 1st argument
src/b1_timing.cpp:197:11: error: no viable overloaded '='
    ct1_b1=std::chrono::system_clock::now();//start timing of one iteration for b1
    ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/chrono:750:29: note: candidate function
      (the implicit copy assignment operator) not viable: no known conversion from 'time_point<std::__1::chrono::system_clock, duration<[...],
      ratio<[...], 1000000>>>' to 'const time_point<std::__1::chrono::steady_clock, duration<[...], ratio<[...], 1000000000>>>' for 1st
      argument
class _LIBCPP_TYPE_VIS_ONLY time_point
                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/chrono:750:29: note: candidate function
      (the implicit move assignment operator) not viable: no known conversion from 'time_point<std::__1::chrono::system_clock, duration<[...],
      ratio<[...], 1000000>>>' to 'time_point<std::__1::chrono::steady_clock, duration<[...], ratio<[...], 1000000000>>>' for 1st argument
src/b1_timing.cpp:208:11: error: no viable overloaded '='
    ct2_b1=std::chrono::system_clock::now();//end timing of one iteration for b1
    ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/chrono:750:29: note: candidate function
      (the implicit copy assignment operator) not viable: no known conversion from 'time_point<std::__1::chrono::system_clock, duration<[...],
      ratio<[...], 1000000>>>' to 'const time_point<std::__1::chrono::steady_clock, duration<[...], ratio<[...], 1000000000>>>' for 1st
      argument
class _LIBCPP_TYPE_VIS_ONLY time_point
                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/chrono:750:29: note: candidate function
      (the implicit move assignment operator) not viable: no known conversion from 'time_point<std::__1::chrono::system_clock, duration<[...],
      ratio<[...], 1000000>>>' to 'time_point<std::__1::chrono::steady_clock, duration<[...], ratio<[...], 1000000000>>>' for 1st argument
src/b1_timing.cpp:211:11: error: no viable overloaded '='
    ct1_b2=std::chrono::system_clock::now();//start timing of one iteration for b2
    ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/chrono:750:29: note: candidate function
      (the implicit copy assignment operator) not viable: no known conversion from 'time_point<std::__1::chrono::system_clock, duration<[...],
      ratio<[...], 1000000>>>' to 'const time_point<std::__1::chrono::steady_clock, duration<[...], ratio<[...], 1000000000>>>' for 1st
      argument
class _LIBCPP_TYPE_VIS_ONLY time_point
                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/chrono:750:29: note: candidate function
      (the implicit move assignment operator) not viable: no known conversion from 'time_point<std::__1::chrono::system_clock, duration<[...],
      ratio<[...], 1000000>>>' to 'time_point<std::__1::chrono::steady_clock, duration<[...], ratio<[...], 1000000000>>>' for 1st argument
src/b1_timing.cpp:219:11: error: no viable overloaded '='
    ct2_b2=std::chrono::system_clock::now();//end timing of one iteration for b2
    ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/chrono:750:29: note: candidate function
      (the implicit copy assignment operator) not viable: no known conversion from 'time_point<std::__1::chrono::system_clock, duration<[...],
      ratio<[...], 1000000>>>' to 'const time_point<std::__1::chrono::steady_clock, duration<[...], ratio<[...], 1000000000>>>' for 1st
      argument
class _LIBCPP_TYPE_VIS_ONLY time_point
                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/chrono:750:29: note: candidate function
      (the implicit move assignment operator) not viable: no known conversion from 'time_point<std::__1::chrono::system_clock, duration<[...],
      ratio<[...], 1000000>>>' to 'time_point<std::__1::chrono::steady_clock, duration<[...], ratio<[...], 1000000000>>>' for 1st argument
src/b1_timing.cpp:249:12: error: no viable overloaded '='
    for_end=std::chrono::system_clock::now();//end total timing of for-loop
    ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/chrono:750:29: note: candidate function
      (the implicit copy assignment operator) not viable: no known conversion from 'time_point<std::__1::chrono::system_clock, duration<[...],
      ratio<[...], 1000000>>>' to 'const time_point<std::__1::chrono::steady_clock, duration<[...], ratio<[...], 1000000000>>>' for 1st
      argument
class _LIBCPP_TYPE_VIS_ONLY time_point
                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/chrono:750:29: note: candidate function
      (the implicit move assignment operator) not viable: no known conversion from 'time_point<std::__1::chrono::system_clock, duration<[...],
      ratio<[...], 1000000>>>' to 'time_point<std::__1::chrono::steady_clock, duration<[...], ratio<[...], 1000000000>>>' for 1st argument
6 errors generated.
make[1]: *** [src/b1_timing-b1_timing.o] Error 1
make: *** [all] Error 2
```

**Comment by ofloveandhate** [comment]
see https://github.com/ebemunk/phoenix/commit/bff0eb5c0e40f19a96049cf35249863ec9164aec

**Comment by ofloveandhate** [comment]
yep, can be fixed with 
`std::chrono::system_clock::now` 
-->
`std::chrono::high_resolution_clock::now`

**Comment by fpancald** [comment]
I have never tried this code on anything else than the crc system at Notre Dame using gcc. 
I never got that error on my hand before.
I think this is due to the fact that apparently, I am initializing the time_point variables with high_resolution_clock and in the rest of the code I am using system_clock. I think I might have changed one and forgot to change the others at some point, but on the crc I was not getting an error.
Should I change it and submit a new pull request? 
Did you get any other errors once you entered that change?

**Comment by ofloveandhate** [comment]
just keep making commits to your branch on your repo.  the PR picks them up, no need to make a new one this time.
no, i got no other compile-time errors, though it did segfault  😦  when i ran the program with no inputs...  can you add some code guarding against using the value of `Args[3]`, for example, when the user did not supply such an argument?  it can be a default value, or just a simple `if (nArgs < 4)` block.

**Comment by fpancald** [comment]
both system_clock issue and number of arguments issue should be solved now. 
If there is still problems with these or other issues let me know. :)

**Comment by ofloveandhate** [comment]
close.  now `prec_b1`, `size`, and `iter` are scoped in `{}` and are not available later...  try this:

```
int prec_b1, size, iter;
	if(nArgs<4)
	{
		prec_b1=1024;
        size=10;
        iter=1;//test parameters: prec_b1= bit precision, size=square matrix size, iter=number of repetition
		std::cout << "Not enough arguments entered.\n Program will be executed with default parameters.\n bit_precision="<<prec_b1<<", size="<<size<<", iterations="<<iter<<" \n";
	}
	else	
	{
		prec_b1=atoi(Args[1]);
        size=atoi(Args[2]);
        iter=atoi(Args[3]);
	}
```

**Comment by fpancald** [comment]
Yes. I meant to do that actually. Thanks for pointing this out.
The other issue with chrono works OK on your side now?
If you see any other problems let me know.

**Comment by ofloveandhate** [comment]
got there.  this seems good.  the code is pretty dirty (lots of leftover comments and things).  do you want to clean it up at all before I accept?  or would you like me to take it as-is?

**Comment by fpancald** [comment]
Yes. I know there is still some leftover comments and commented out old pieces of code. Some of them will be removed and some modified soon. 
For now please accept it as-is. When I am putting together the documentation I will also tidy it up (probably next Monday).

**Comment by ofloveandhate** [comment]
accepted

**Pull request merged**
